# Genetic Algorithm Configuration
genetic_algorithm:
  pop_size: 10
  generations: 10
  crossover_rate: 0.9
  mutation_rate: 0.02
  crossover_alpha: 0.5
  mutation_sigma: 3.0
  elitism: 2
  tournament_k: 3
  maximize: false
  seed: 42

# Simulation Parameters
simulation:
  spin_number: 1000000
  target_rtp: 0.45
  target_hit_frequency: 0.10

# Reel Generation Configuration
reel_generation:
  reels:  
    - radius: 3 #1 
      seed: 1
      symbol_stacks:
        low:
          0: [1, 0, 0, 0]
          1: [1, 0, 0, 0]
          2: [0, 0, 0, 0]
          3: [0, 0, 0, 0]
          4: [0, 0, 0, 0]
          5: [0, 0, 0, 0]
          6: [0, 0, 0, 0]
          7: [0, 0, 0, 0]
          8: [0, 0, 0, 0]
          9: [0, 0, 0, 0]
        high:
          0: [5, 0, 0, 0]
          1: [5, 0, 0, 0]
          2: [20, 20, 20, 20]
          3: [20, 20, 20, 20]
          4: [20, 20, 20, 20]
          5: [20, 20, 20, 20]
          6: [20, 20, 20, 20]
          7: [20, 20, 20, 20]
          8: [20, 20, 20, 20]
          9: [20, 20, 20, 20]
    - radius: 3 #2
      seed: 2
      symbol_stacks:
        low:
          0: [1, 0, 0, 0]
          1: [1, 0, 0, 0]
          2: [0, 0, 0, 0]
          3: [0, 0, 0, 0]
          4: [0, 0, 0, 0]
          5: [0, 0, 0, 0]
          6: [0, 0, 0, 0]
          7: [0, 0, 0, 0]
          8: [0, 0, 0, 0]
          9: [0, 0, 0, 0]
        high:
          0: [5, 0, 0, 0]
          1: [5, 0, 0, 0]
          2: [20, 20, 20, 20]
          3: [20, 20, 20, 20]
          4: [20, 20, 20, 20]
          5: [20, 20, 20, 20]
          6: [20, 20, 20, 20]
          7: [20, 20, 20, 20]
          8: [20, 20, 20, 20]
          9: [20, 20, 20, 20]
    - radius: 3 #3
      seed: 3
      symbol_stacks:
        low:
          0: [1, 0, 0, 0]
          1: [1, 0, 0, 0]
          2: [0, 0, 0, 0]
          3: [0, 0, 0, 0]
          4: [0, 0, 0, 0]
          5: [0, 0, 0, 0]
          6: [0, 0, 0, 0]
          7: [0, 0, 0, 0]
          8: [0, 0, 0, 0]
          9: [0, 0, 0, 0]
        high:
          0: [5, 0, 0, 0]
          1: [5, 0, 0, 0]
          2: [20, 20, 20, 20]
          3: [20, 20, 20, 20]
          4: [20, 20, 20, 20]
          5: [20, 20, 20, 20]
          6: [20, 20, 20, 20]
          7: [20, 20, 20, 20]
          8: [20, 20, 20, 20]
          9: [20, 20, 20, 20]

    - radius: 3 #4
      seed: 3
      symbol_stacks:
        low:
          0: [1, 0, 0, 0]
          1: [1, 0, 0, 0]
          2: [0, 0, 0, 0]
          3: [0, 0, 0, 0]
          4: [0, 0, 0, 0]
          5: [0, 0, 0, 0]
          6: [0, 0, 0, 0]
          7: [0, 0, 0, 0]
          8: [0, 0, 0, 0]
          9: [0, 0, 0, 0]
        high:
          0: [5, 0, 0, 0]
          1: [5, 0, 0, 0]
          2: [20, 20, 20, 20]
          3: [20, 20, 20, 20]
          4: [20, 20, 20, 20]
          5: [20, 20, 20, 20]
          6: [20, 20, 20, 20]
          7: [20, 20, 20, 20]
          8: [20, 20, 20, 20]
          9: [20, 20, 20, 20]

    - radius: 3 #5
      seed: 3
      symbol_stacks:
        low:
          0: [1, 0, 0, 0]
          1: [1, 0, 0, 0]
          2: [0, 0, 0, 0]
          3: [0, 0, 0, 0]
          4: [0, 0, 0, 0]
          5: [0, 0, 0, 0]
          6: [0, 0, 0, 0]
          7: [0, 0, 0, 0]
          8: [0, 0, 0, 0]
          9: [0, 0, 0, 0]
        high:
          0: [5, 0, 0, 0]
          1: [5, 0, 0, 0]
          2: [20, 20, 20, 20]
          3: [20, 20, 20, 20]
          4: [20, 20, 20, 20]
          5: [20, 20, 20, 20]
          6: [20, 20, 20, 20]
          7: [20, 20, 20, 20]
          8: [20, 20, 20, 20]
          9: [20, 20, 20, 20]

# Slot Machine Configuration
slot_machine:
  window: [4, 4, 4, 4, 4]
  icon_wild: [0]
  icon_scatter: [1]

  # Paytable structure
  paytable:
    0:  [0, 0, 10, 100, 200]
    1:  [0, 0, 0, 0, 0]
    2:  [0, 0, 10, 100, 200]
    3:  [0, 0, 8, 40, 120]
    4:  [0, 0, 6, 30, 100]
    5:  [0, 0, 4, 20, 60]
    6:  [0, 0, 4, 8, 20]
    7:  [0, 0, 4, 8, 20]
    8:  [0, 0, 4, 8, 20]
    9:  [0, 0, 4, 8, 20]
  
  # Pay lines
  lines:
   - [0, 0, 0, 0, 0]
   - [1, 1, 1, 1, 1]
   - [2, 2, 2, 2, 2]
   - [3, 3, 3, 3, 3]
   - [0, 1, 2, 1, 0]
   - [1, 2, 3, 2, 1]
   - [2, 1, 0, 1, 2]
   - [3, 2, 1, 2, 3]
   - [0, 1, 0, 1, 0]
   - [1, 2, 1, 2, 1]
   - [2, 3, 2, 3, 2]
   - [1, 0, 1, 0, 1]
   - [2, 1, 2, 1, 2]
   - [3, 2, 3, 2, 3]
   - [0, 1, 1, 1, 0]
   - [1, 2, 2, 2, 1]
   - [2, 3, 3, 3, 2]
   - [1, 0, 0, 0, 1]
   - [2, 1, 1, 1, 2]
   - [3, 2, 2, 2, 3]
   - [0, 0, 1, 0, 0]
   - [1, 1, 2, 1, 1]
   - [2, 2, 3, 2, 2]
   - [1, 1, 0, 0, 0]
   - [2, 2, 1, 2, 2]
