genetic_algorithm:
  pop_size: 64
  generations: 160
  crossover_rate: 0.9
  mutation_rate: 0.06
  crossover_alpha: 0.4
  mutation_sigma: 2.4
  elitism: 3
  tournament_k: 3
  seed: 73

simulation:
  spin_number: 1000000
  target_rtp: 0.42
  target_hit_frequency: 0.15
  target_bonus_game_frequency: 0.0066
  symbol_rtp_unevenness_weight: 1
  symbol_rtp_targets:
    2: 0.015
    3: 0.020
    4: 0.030
    5: 0.040
    6: 0.070
    7: 0.070
    8: 0.070


reel_generation:
  reels:
    - radius: 3
      seed: 11
      symbol_stacks:
        low:
          0: [1, 0, 0]
          1: [1, 0, 0]
          2: [0, 0, 1]
          3: [0, 0, 1]
          4: [0, 0, 1]
          5: [0, 0, 1]
          6: [1, 1, 1]
          7: [1, 1, 1]
          8: [1, 1, 1]
          9: [1, 1, 1]
        high:
          0: [10, 0, 0]
          1: [10, 10, 10]
          2: [2, 2, 2]
          3: [3, 3, 3]
          4: [4, 4, 4]
          5: [5, 5, 5]
          6: [10, 10, 10]
          7: [10, 10, 10]
          8: [10, 10, 10]
          9: [10, 10, 10]
    - radius: 3
      seed: 12
      symbol_stacks:
        low:
          0: [1, 0, 0]
          1: [1, 0, 0]
          2: [0, 0, 1]
          3: [0, 0, 1]
          4: [0, 0, 1]
          5: [0, 0, 1]
          6: [1, 1, 1]
          7: [1, 1, 1]
          8: [1, 1, 1]
          9: [1, 1, 1]
        high:
          0: [10, 0, 0]
          1: [10, 0, 0]
          2: [2, 2, 2]
          3: [3, 3, 3]
          4: [4, 4, 4]
          5: [5, 5, 5]
          6: [10, 10, 10]
          7: [10, 10, 10]
          8: [10, 10, 10]
          9: [10, 10, 10]
    - radius: 3
      seed: 13
      symbol_stacks:
        low:
          0: [1, 0, 0]
          1: [1, 0, 0]
          2: [0, 0, 1]
          3: [0, 0, 1]
          4: [0, 0, 1]
          5: [0, 0, 1]
          6: [1, 1, 1]
          7: [1, 1, 1]
          8: [1, 1, 1]
          9: [1, 1, 1]
        high:
          0: [10, 0, 0]
          1: [10, 10, 10]
          2: [2, 2, 2]
          3: [3, 3, 3]
          4: [4, 4, 4]
          5: [5, 5, 5]
          6: [10, 10, 10]
          7: [10, 10, 10]
          8: [10, 10, 10]
          9: [10, 10, 10]

slot_machine:
  window: [3, 3, 3]
  icon_wild: [0]
  icon_scatter: [1]
  paytable:
    0: [0, 0, 50]
    1: [0, 0, 0]
    2: [0, 0, 30]
    3: [0, 0, 20]
    4: [0, 0, 16]
    5: [0, 0, 16]
    6: [0, 0, 4]
    7: [0, 0, 4]
    8: [0, 0, 4]
    9: [0, 0, 1]
  lines:
    - [0, 0, 0]
    - [1, 1, 1]
    - [2, 2, 2]
    - [0, 1, 2]
    - [2, 1, 0]
